// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: log_event_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cat.durban.sergio.flutter_meta_appads_sdk.proto;

@kotlin.jvm.JvmName("-initializeeventParameter")
public inline fun eventParameter(block: cat.durban.sergio.flutter_meta_appads_sdk.proto.EventParameterKt.Dsl.() -> kotlin.Unit): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter =
  cat.durban.sergio.flutter_meta_appads_sdk.proto.EventParameterKt.Dsl._create(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `EventParameter`
 */
public object EventParameterKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string value = 2;`
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `string value = 2;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter.copy(block: `cat.durban.sergio.flutter_meta_appads_sdk.proto`.EventParameterKt.Dsl.() -> kotlin.Unit): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.EventParameter =
  `cat.durban.sergio.flutter_meta_appads_sdk.proto`.EventParameterKt.Dsl._create(this.toBuilder()).apply { block() }._build()

