// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: log_standard_event_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cat.durban.sergio.flutter_meta_appads_sdk.proto;

@kotlin.jvm.JvmName("-initializefBDefaultParameter")
public inline fun fBDefaultParameter(block: cat.durban.sergio.flutter_meta_appads_sdk.proto.FBDefaultParameterKt.Dsl.() -> kotlin.Unit): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter =
  cat.durban.sergio.flutter_meta_appads_sdk.proto.FBDefaultParameterKt.Dsl._create(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `FBDefaultParameter`
 */
public object FBDefaultParameterKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter = _builder.build()

    /**
     * `.FBStandardParameters parameterName = 1;`
     */
    public var parameterName: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters
      @JvmName("getParameterName")
      get() = _builder.getParameterName()
      @JvmName("setParameterName")
      set(value) {
        _builder.setParameterName(value)
      }
    public var parameterNameValue: kotlin.Int
      @JvmName("getParameterNameValue")
      get() = _builder.getParameterNameValue()
      @JvmName("setParameterNameValue")
      set(value) {
        _builder.setParameterNameValue(value)
      }
    /**
     * `.FBStandardParameters parameterName = 1;`
     */
    public fun clearParameterName() {
      _builder.clearParameterName()
    }

    /**
     * `string value = 2;`
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `string value = 2;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.copy(block: `cat.durban.sergio.flutter_meta_appads_sdk.proto`.FBDefaultParameterKt.Dsl.() -> kotlin.Unit): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter =
  `cat.durban.sergio.flutter_meta_appads_sdk.proto`.FBDefaultParameterKt.Dsl._create(this.toBuilder()).apply { block() }._build()

