// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: log_standard_event_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cat.durban.sergio.flutter_meta_appads_sdk.proto;

@kotlin.jvm.JvmName("-initializefBLogStandardEventMessageRequest")
public inline fun fBLogStandardEventMessageRequest(block: cat.durban.sergio.flutter_meta_appads_sdk.proto.FBLogStandardEventMessageRequestKt.Dsl.() -> kotlin.Unit): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest =
  cat.durban.sergio.flutter_meta_appads_sdk.proto.FBLogStandardEventMessageRequestKt.Dsl._create(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `FBLogStandardEventMessageRequest`
 */
public object FBLogStandardEventMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest = _builder.build()

    /**
     * `.FBStandardEvents eventName = 1;`
     */
    public var eventName: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents
      @JvmName("getEventName")
      get() = _builder.getEventName()
      @JvmName("setEventName")
      set(value) {
        _builder.setEventName(value)
      }
    public var eventNameValue: kotlin.Int
      @JvmName("getEventNameValue")
      get() = _builder.getEventNameValue()
      @JvmName("setEventNameValue")
      set(value) {
        _builder.setEventNameValue(value)
      }
    /**
     * `.FBStandardEvents eventName = 1;`
     */
    public fun clearEventName() {
      _builder.clearEventName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EventParameterProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     */
     public val eventParameter: com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEventParameterList()
      )
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     * @param value The eventParameter to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEventParameter")
    public fun com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>.add(value: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter) {
      _builder.addEventParameter(value)
    }
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     * @param value The eventParameter to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEventParameter")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>.plusAssign(value: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter) {
      add(value)
    }
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     * @param values The eventParameter to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEventParameter")
    public fun com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>.addAll(values: kotlin.collections.Iterable<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter>) {
      _builder.addAllEventParameter(values)
    }
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     * @param values The eventParameter to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEventParameter")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>.plusAssign(values: kotlin.collections.Iterable<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter>) {
      addAll(values)
    }
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     * @param index The index to set the value at.
     * @param value The eventParameter to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEventParameter")
    public operator fun com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>.set(index: kotlin.Int, value: cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter) {
      _builder.setEventParameter(index, value)
    }
    /**
     * `repeated .FBDefaultParameter eventParameter = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEventParameter")
    public fun com.google.protobuf.kotlin.DslList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, EventParameterProxy>.clear() {
      _builder.clearEventParameter()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.copy(block: `cat.durban.sergio.flutter_meta_appads_sdk.proto`.FBLogStandardEventMessageRequestKt.Dsl.() -> kotlin.Unit): cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest =
  `cat.durban.sergio.flutter_meta_appads_sdk.proto`.FBLogStandardEventMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

