// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: log_purchase_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cat.durban.sergio.flutter_meta_appads_sdk.proto;

