// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fb_anon_id_message.proto
// Protobuf Java Version: 4.29.3

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class FbAnonIdMessage {
  private FbAnonIdMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FBAnonIdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBAnonIdResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string fbAnonId = 1;</code>
     * @return The fbAnonId.
     */
    java.lang.String getFbAnonId();
    /**
     * <code>string fbAnonId = 1;</code>
     * @return The bytes for fbAnonId.
     */
    com.google.protobuf.ByteString
        getFbAnonIdBytes();
  }
  /**
   * Protobuf type {@code FBAnonIdResponse}
   */
  public  static final class FBAnonIdResponse extends
      com.google.protobuf.GeneratedMessageLite<
          FBAnonIdResponse, FBAnonIdResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:FBAnonIdResponse)
      FBAnonIdResponseOrBuilder {
    private FBAnonIdResponse() {
      fbAnonId_ = "";
    }
    public static final int FBANONID_FIELD_NUMBER = 1;
    private java.lang.String fbAnonId_;
    /**
     * <code>string fbAnonId = 1;</code>
     * @return The fbAnonId.
     */
    @java.lang.Override
    public java.lang.String getFbAnonId() {
      return fbAnonId_;
    }
    /**
     * <code>string fbAnonId = 1;</code>
     * @return The bytes for fbAnonId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFbAnonIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fbAnonId_);
    }
    /**
     * <code>string fbAnonId = 1;</code>
     * @param value The fbAnonId to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setFbAnonId(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      fbAnonId_ = value;
    }
    /**
     * <code>string fbAnonId = 1;</code>
     */
    private void clearFbAnonId() {

      fbAnonId_ = getDefaultInstance().getFbAnonId();
    }
    /**
     * <code>string fbAnonId = 1;</code>
     * @param value The bytes for fbAnonId to set.
     */
    private void setFbAnonIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fbAnonId_ = value.toStringUtf8();

    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code FBAnonIdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:FBAnonIdResponse)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponseOrBuilder {
      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string fbAnonId = 1;</code>
       * @return The fbAnonId.
       */
      @java.lang.Override
      public java.lang.String getFbAnonId() {
        return instance.getFbAnonId();
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @return The bytes for fbAnonId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFbAnonIdBytes() {
        return instance.getFbAnonIdBytes();
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @param value The fbAnonId to set.
       * @return This builder for chaining.
       */
      public Builder setFbAnonId(
          java.lang.String value) {
        copyOnWrite();
        instance.setFbAnonId(value);
        return this;
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFbAnonId() {
        copyOnWrite();
        instance.clearFbAnonId();
        return this;
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @param value The bytes for fbAnonId to set.
       * @return This builder for chaining.
       */
      public Builder setFbAnonIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFbAnonIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBAnonIdResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "fbAnonId_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse> parser = PARSER;
          if (parser == null) {
            synchronized (cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:FBAnonIdResponse)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse DEFAULT_INSTANCE;
    static {
      FBAnonIdResponse defaultInstance = new FBAnonIdResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FBAnonIdResponse.class, defaultInstance);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FBAnonIdResponse> PARSER;

    public static com.google.protobuf.Parser<FBAnonIdResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
