// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fb_anon_id_message.proto
// Protobuf Java Version: 4.26.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class FbAnonIdMessage {
  private FbAnonIdMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      FbAnonIdMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FBAnonIdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBAnonIdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fbAnonId = 1;</code>
     * @return The fbAnonId.
     */
    java.lang.String getFbAnonId();
    /**
     * <code>string fbAnonId = 1;</code>
     * @return The bytes for fbAnonId.
     */
    com.google.protobuf.ByteString
        getFbAnonIdBytes();
  }
  /**
   * Protobuf type {@code FBAnonIdResponse}
   */
  public static final class FBAnonIdResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FBAnonIdResponse)
      FBAnonIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBAnonIdResponse.class.getName());
    }
    // Use FBAnonIdResponse.newBuilder() to construct.
    private FBAnonIdResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FBAnonIdResponse() {
      fbAnonId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.internal_static_FBAnonIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.internal_static_FBAnonIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.Builder.class);
    }

    public static final int FBANONID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fbAnonId_ = "";
    /**
     * <code>string fbAnonId = 1;</code>
     * @return The fbAnonId.
     */
    @java.lang.Override
    public java.lang.String getFbAnonId() {
      java.lang.Object ref = fbAnonId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fbAnonId_ = s;
        return s;
      }
    }
    /**
     * <code>string fbAnonId = 1;</code>
     * @return The bytes for fbAnonId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFbAnonIdBytes() {
      java.lang.Object ref = fbAnonId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fbAnonId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fbAnonId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, fbAnonId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fbAnonId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, fbAnonId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse)) {
        return super.equals(obj);
      }
      cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse other = (cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse) obj;

      if (!getFbAnonId()
          .equals(other.getFbAnonId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FBANONID_FIELD_NUMBER;
      hash = (53 * hash) + getFbAnonId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FBAnonIdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FBAnonIdResponse)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.internal_static_FBAnonIdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.internal_static_FBAnonIdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.Builder.class);
      }

      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fbAnonId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.internal_static_FBAnonIdResponse_descriptor;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse getDefaultInstanceForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse build() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse buildPartial() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse result = new cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fbAnonId_ = fbAnonId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse) {
          return mergeFrom((cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse other) {
        if (other == cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse.getDefaultInstance()) return this;
        if (!other.getFbAnonId().isEmpty()) {
          fbAnonId_ = other.fbAnonId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fbAnonId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fbAnonId_ = "";
      /**
       * <code>string fbAnonId = 1;</code>
       * @return The fbAnonId.
       */
      public java.lang.String getFbAnonId() {
        java.lang.Object ref = fbAnonId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fbAnonId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @return The bytes for fbAnonId.
       */
      public com.google.protobuf.ByteString
          getFbAnonIdBytes() {
        java.lang.Object ref = fbAnonId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fbAnonId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @param value The fbAnonId to set.
       * @return This builder for chaining.
       */
      public Builder setFbAnonId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fbAnonId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFbAnonId() {
        fbAnonId_ = getDefaultInstance().getFbAnonId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string fbAnonId = 1;</code>
       * @param value The bytes for fbAnonId to set.
       * @return This builder for chaining.
       */
      public Builder setFbAnonIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fbAnonId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBAnonIdResponse)
    }

    // @@protoc_insertion_point(class_scope:FBAnonIdResponse)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FBAnonIdResponse>
        PARSER = new com.google.protobuf.AbstractParser<FBAnonIdResponse>() {
      @java.lang.Override
      public FBAnonIdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FBAnonIdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FBAnonIdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.FbAnonIdMessage.FBAnonIdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBAnonIdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBAnonIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030fb_anon_id_message.proto\"$\n\020FBAnonIdRe" +
      "sponse\022\020\n\010fbAnonId\030\001 \001(\tB1\n/cat.durban.s" +
      "ergio.flutter_meta_appads_sdk.protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FBAnonIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FBAnonIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBAnonIdResponse_descriptor,
        new java.lang.String[] { "FbAnonId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
