// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_event_message.proto
// Protobuf Java Version: 4.26.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class LogEventMessage {
  private LogEventMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      LogEventMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FBLogEventMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBLogEventMessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string eventName = 1;</code>
     * @return The eventName.
     */
    java.lang.String getEventName();
    /**
     * <code>string eventName = 1;</code>
     * @return The bytes for eventName.
     */
    com.google.protobuf.ByteString
        getEventNameBytes();

    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    int getEventParameterCount();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    boolean containsEventParameter(
        java.lang.String key);
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameter();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameterMap();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    java.lang.String getEventParameterOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code FBLogEventMessageRequest}
   */
  public static final class FBLogEventMessageRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FBLogEventMessageRequest)
      FBLogEventMessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBLogEventMessageRequest.class.getName());
    }
    // Use FBLogEventMessageRequest.newBuilder() to construct.
    private FBLogEventMessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FBLogEventMessageRequest() {
      eventName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.internal_static_FBLogEventMessageRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetEventParameter();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.internal_static_FBLogEventMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.Builder.class);
    }

    public static final int EVENTNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eventName_ = "";
    /**
     * <code>string eventName = 1;</code>
     * @return The eventName.
     */
    @java.lang.Override
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      }
    }
    /**
     * <code>string eventName = 1;</code>
     * @return The bytes for eventName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 2;
    private static final class EventParameterDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.internal_static_FBLogEventMessageRequest_EventParameterEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> eventParameter_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetEventParameter() {
      if (eventParameter_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventParameterDefaultEntryHolder.defaultEntry);
      }
      return eventParameter_;
    }
    public int getEventParameterCount() {
      return internalGetEventParameter().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public boolean containsEventParameter(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEventParameter().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
      return getEventParameterMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
      return internalGetEventParameter().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getEventParameterOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, eventName_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetEventParameter(),
          EventParameterDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, eventName_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetEventParameter().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        eventParameter__ = EventParameterDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, eventParameter__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest)) {
        return super.equals(obj);
      }
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest other = (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest) obj;

      if (!getEventName()
          .equals(other.getEventName())) return false;
      if (!internalGetEventParameter().equals(
          other.internalGetEventParameter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getEventName().hashCode();
      if (!internalGetEventParameter().getMap().isEmpty()) {
        hash = (37 * hash) + EVENTPARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEventParameter().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FBLogEventMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FBLogEventMessageRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.internal_static_FBLogEventMessageRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetEventParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableEventParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.internal_static_FBLogEventMessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.Builder.class);
      }

      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        eventName_ = "";
        internalGetMutableEventParameter().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.internal_static_FBLogEventMessageRequest_descriptor;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest getDefaultInstanceForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest build() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest buildPartial() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest result = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.eventName_ = eventName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.eventParameter_ = internalGetEventParameter();
          result.eventParameter_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest) {
          return mergeFrom((cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest other) {
        if (other == cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.getDefaultInstance()) return this;
        if (!other.getEventName().isEmpty()) {
          eventName_ = other.eventName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        internalGetMutableEventParameter().mergeFrom(
            other.internalGetEventParameter());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                eventName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                eventParameter__ = input.readMessage(
                    EventParameterDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableEventParameter().getMutableMap().put(
                    eventParameter__.getKey(), eventParameter__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object eventName_ = "";
      /**
       * <code>string eventName = 1;</code>
       * @return The eventName.
       */
      public java.lang.String getEventName() {
        java.lang.Object ref = eventName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eventName = 1;</code>
       * @return The bytes for eventName.
       */
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        java.lang.Object ref = eventName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eventName = 1;</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eventName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string eventName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        eventName_ = getDefaultInstance().getEventName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string eventName = 1;</code>
       * @param value The bytes for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eventName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> eventParameter_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetEventParameter() {
        if (eventParameter_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EventParameterDefaultEntryHolder.defaultEntry);
        }
        return eventParameter_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableEventParameter() {
        if (eventParameter_ == null) {
          eventParameter_ = com.google.protobuf.MapField.newMapField(
              EventParameterDefaultEntryHolder.defaultEntry);
        }
        if (!eventParameter_.isMutable()) {
          eventParameter_ = eventParameter_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return eventParameter_;
      }
      public int getEventParameterCount() {
        return internalGetEventParameter().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public boolean containsEventParameter(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetEventParameter().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEventParameterMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
        return getEventParameterMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
        return internalGetEventParameter().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getEventParameterOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetEventParameter().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getEventParameterOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetEventParameter().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearEventParameter() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableEventParameter().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder removeEventParameter(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableEventParameter().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableEventParameter() {
        bitField0_ |= 0x00000002;
        return internalGetMutableEventParameter().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder putEventParameter(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableEventParameter().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder putAllEventParameter(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableEventParameter().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBLogEventMessageRequest)
    }

    // @@protoc_insertion_point(class_scope:FBLogEventMessageRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FBLogEventMessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<FBLogEventMessageRequest>() {
      @java.lang.Override
      public FBLogEventMessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FBLogEventMessageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FBLogEventMessageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBLogEventMessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBLogEventMessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBLogEventMessageRequest_EventParameterEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBLogEventMessageRequest_EventParameterEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027log_event_message.proto\"\253\001\n\030FBLogEvent" +
      "MessageRequest\022\021\n\teventName\030\001 \001(\t\022E\n\016eve" +
      "ntParameter\030\002 \003(\0132-.FBLogEventMessageReq" +
      "uest.EventParameterEntry\0325\n\023EventParamet" +
      "erEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B" +
      "1\n/cat.durban.sergio.flutter_meta_appads" +
      "_sdk.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FBLogEventMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FBLogEventMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBLogEventMessageRequest_descriptor,
        new java.lang.String[] { "EventName", "EventParameter", });
    internal_static_FBLogEventMessageRequest_EventParameterEntry_descriptor =
      internal_static_FBLogEventMessageRequest_descriptor.getNestedTypes().get(0);
    internal_static_FBLogEventMessageRequest_EventParameterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBLogEventMessageRequest_EventParameterEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
