// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: log_event_message.proto
// Protobuf Java Version: 4.29.3

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class LogEventMessage {
  private LogEventMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FBLogEventMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBLogEventMessageRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string eventName = 1;</code>
     * @return The eventName.
     */
    java.lang.String getEventName();
    /**
     * <code>string eventName = 1;</code>
     * @return The bytes for eventName.
     */
    com.google.protobuf.ByteString
        getEventNameBytes();

    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    int getEventParameterCount();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    boolean containsEventParameter(
        java.lang.String key);
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameter();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameterMap();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */

    /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */

    java.lang.String getEventParameterOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code FBLogEventMessageRequest}
   */
  public  static final class FBLogEventMessageRequest extends
      com.google.protobuf.GeneratedMessageLite<
          FBLogEventMessageRequest, FBLogEventMessageRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:FBLogEventMessageRequest)
      FBLogEventMessageRequestOrBuilder {
    private FBLogEventMessageRequest() {
      eventName_ = "";
    }
    public static final int EVENTNAME_FIELD_NUMBER = 1;
    private java.lang.String eventName_;
    /**
     * <code>string eventName = 1;</code>
     * @return The eventName.
     */
    @java.lang.Override
    public java.lang.String getEventName() {
      return eventName_;
    }
    /**
     * <code>string eventName = 1;</code>
     * @return The bytes for eventName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(eventName_);
    }
    /**
     * <code>string eventName = 1;</code>
     * @param value The eventName to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setEventName(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      eventName_ = value;
    }
    /**
     * <code>string eventName = 1;</code>
     */
    private void clearEventName() {

      eventName_ = getDefaultInstance().getEventName();
    }
    /**
     * <code>string eventName = 1;</code>
     * @param value The bytes for eventName to set.
     */
    private void setEventNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      eventName_ = value.toStringUtf8();

    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 2;
    private static final class EventParameterDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> eventParameter_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetEventParameter() {
      return eventParameter_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableEventParameter() {
      if (!eventParameter_.isMutable()) {
        eventParameter_ = eventParameter_.mutableCopy();
      }
      return eventParameter_;
    }
    @java.lang.Override

    public int getEventParameterCount() {
      return internalGetEventParameter().size();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override

    public boolean containsEventParameter(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return internalGetEventParameter().containsKey(key);
    }
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
      return getEventParameterMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetEventParameter());
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getEventParameterOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableEventParameterMap() {
      return internalGetMutableEventParameter();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code FBLogEventMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:FBLogEventMessageRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequestOrBuilder {
      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string eventName = 1;</code>
       * @return The eventName.
       */
      @java.lang.Override
      public java.lang.String getEventName() {
        return instance.getEventName();
      }
      /**
       * <code>string eventName = 1;</code>
       * @return The bytes for eventName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        return instance.getEventNameBytes();
      }
      /**
       * <code>string eventName = 1;</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(
          java.lang.String value) {
        copyOnWrite();
        instance.setEventName(value);
        return this;
      }
      /**
       * <code>string eventName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        copyOnWrite();
        instance.clearEventName();
        return this;
      }
      /**
       * <code>string eventName = 1;</code>
       * @param value The bytes for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEventNameBytes(value);
        return this;
      }

      @java.lang.Override

      public int getEventParameterCount() {
        return instance.getEventParameterMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override

      public boolean containsEventParameter(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        return instance.getEventParameterMap().containsKey(key);
      }

      public Builder clearEventParameter() {
        copyOnWrite();
        instance.getMutableEventParameterMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */

      public Builder removeEventParameter(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        copyOnWrite();
        instance.getMutableEventParameterMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getEventParameterMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
        return getEventParameterMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getEventParameterMap());
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override

      public /* nullable */
java.lang.String getEventParameterOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getEventParameterMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getEventParameterOrThrow(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getEventParameterMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder putEventParameter(
          java.lang.String key,
          java.lang.String value) {
        java.lang.Class<?> keyClass = key.getClass();
        java.lang.Class<?> valueClass = value.getClass();
        copyOnWrite();
        instance.getMutableEventParameterMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder putAllEventParameter(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableEventParameterMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBLogEventMessageRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "eventName_",
              "eventParameter_",
              EventParameterDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0001\u0000\u0000\u0001\u0208\u00022";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest> parser = PARSER;
          if (parser == null) {
            synchronized (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:FBLogEventMessageRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest DEFAULT_INSTANCE;
    static {
      FBLogEventMessageRequest defaultInstance = new FBLogEventMessageRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FBLogEventMessageRequest.class, defaultInstance);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogEventMessage.FBLogEventMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FBLogEventMessageRequest> PARSER;

    public static com.google.protobuf.Parser<FBLogEventMessageRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
