// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_purchase_message.proto
// Protobuf Java Version: 4.26.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class LogPurchaseMessage {
  private LogPurchaseMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      LogPurchaseMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FBLogPurchaseMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBLogPurchaseMessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    int getEventParameterCount();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    boolean containsEventParameter(
        java.lang.String key);
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameter();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameterMap();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    java.lang.String getEventParameterOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code FBLogPurchaseMessageRequest}
   */
  public static final class FBLogPurchaseMessageRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FBLogPurchaseMessageRequest)
      FBLogPurchaseMessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBLogPurchaseMessageRequest.class.getName());
    }
    // Use FBLogPurchaseMessageRequest.newBuilder() to construct.
    private FBLogPurchaseMessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FBLogPurchaseMessageRequest() {
      currency_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.internal_static_FBLogPurchaseMessageRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetEventParameter();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.internal_static_FBLogPurchaseMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.Builder.class);
    }

    public static final int AMOUNT_FIELD_NUMBER = 1;
    private double amount_ = 0D;
    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    public static final int CURRENCY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object currency_ = "";
    /**
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    @java.lang.Override
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 3;
    private static final class EventParameterDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.internal_static_FBLogPurchaseMessageRequest_EventParameterEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> eventParameter_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetEventParameter() {
      if (eventParameter_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventParameterDefaultEntryHolder.defaultEntry);
      }
      return eventParameter_;
    }
    public int getEventParameterCount() {
      return internalGetEventParameter().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override
    public boolean containsEventParameter(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEventParameter().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
      return getEventParameterMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
      return internalGetEventParameter().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getEventParameterOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        output.writeDouble(1, amount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, currency_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetEventParameter(),
          EventParameterDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, amount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, currency_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetEventParameter().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        eventParameter__ = EventParameterDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, eventParameter__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest)) {
        return super.equals(obj);
      }
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest other = (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest) obj;

      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!getCurrency()
          .equals(other.getCurrency())) return false;
      if (!internalGetEventParameter().equals(
          other.internalGetEventParameter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      if (!internalGetEventParameter().getMap().isEmpty()) {
        hash = (37 * hash) + EVENTPARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEventParameter().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FBLogPurchaseMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FBLogPurchaseMessageRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.internal_static_FBLogPurchaseMessageRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 3:
            return internalGetEventParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableEventParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.internal_static_FBLogPurchaseMessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.Builder.class);
      }

      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        amount_ = 0D;
        currency_ = "";
        internalGetMutableEventParameter().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.internal_static_FBLogPurchaseMessageRequest_descriptor;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest getDefaultInstanceForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest build() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest buildPartial() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest result = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.amount_ = amount_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.currency_ = currency_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.eventParameter_ = internalGetEventParameter();
          result.eventParameter_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest) {
          return mergeFrom((cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest other) {
        if (other == cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.getDefaultInstance()) return this;
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        internalGetMutableEventParameter().mergeFrom(
            other.internalGetEventParameter());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                amount_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 18: {
                currency_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                eventParameter__ = input.readMessage(
                    EventParameterDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableEventParameter().getMutableMap().put(
                    eventParameter__.getKey(), eventParameter__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double amount_ ;
      /**
       * <code>double amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {

        amount_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        amount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 2;</code>
       * @return The currency.
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 2;</code>
       * @return The bytes for currency.
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 2;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        currency_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        currency_ = getDefaultInstance().getCurrency();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 2;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currency_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> eventParameter_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetEventParameter() {
        if (eventParameter_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EventParameterDefaultEntryHolder.defaultEntry);
        }
        return eventParameter_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableEventParameter() {
        if (eventParameter_ == null) {
          eventParameter_ = com.google.protobuf.MapField.newMapField(
              EventParameterDefaultEntryHolder.defaultEntry);
        }
        if (!eventParameter_.isMutable()) {
          eventParameter_ = eventParameter_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return eventParameter_;
      }
      public int getEventParameterCount() {
        return internalGetEventParameter().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override
      public boolean containsEventParameter(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetEventParameter().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEventParameterMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
        return getEventParameterMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
        return internalGetEventParameter().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getEventParameterOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetEventParameter().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getEventParameterOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetEventParameter().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearEventParameter() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableEventParameter().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      public Builder removeEventParameter(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableEventParameter().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableEventParameter() {
        bitField0_ |= 0x00000004;
        return internalGetMutableEventParameter().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      public Builder putEventParameter(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableEventParameter().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      public Builder putAllEventParameter(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableEventParameter().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBLogPurchaseMessageRequest)
    }

    // @@protoc_insertion_point(class_scope:FBLogPurchaseMessageRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FBLogPurchaseMessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<FBLogPurchaseMessageRequest>() {
      @java.lang.Override
      public FBLogPurchaseMessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FBLogPurchaseMessageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FBLogPurchaseMessageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBLogPurchaseMessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBLogPurchaseMessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBLogPurchaseMessageRequest_EventParameterEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBLogPurchaseMessageRequest_EventParameterEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032log_purchase_message.proto\"\300\001\n\033FBLogPu" +
      "rchaseMessageRequest\022\016\n\006amount\030\001 \001(\001\022\020\n\010" +
      "currency\030\002 \001(\t\022H\n\016eventParameter\030\003 \003(\01320" +
      ".FBLogPurchaseMessageRequest.EventParame" +
      "terEntry\0325\n\023EventParameterEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B1\n/cat.durban.se" +
      "rgio.flutter_meta_appads_sdk.protob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FBLogPurchaseMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FBLogPurchaseMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBLogPurchaseMessageRequest_descriptor,
        new java.lang.String[] { "Amount", "Currency", "EventParameter", });
    internal_static_FBLogPurchaseMessageRequest_EventParameterEntry_descriptor =
      internal_static_FBLogPurchaseMessageRequest_descriptor.getNestedTypes().get(0);
    internal_static_FBLogPurchaseMessageRequest_EventParameterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBLogPurchaseMessageRequest_EventParameterEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
