// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: log_purchase_message.proto
// Protobuf Java Version: 4.32.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

@com.google.protobuf.Generated
public final class LogPurchaseMessage {
  private LogPurchaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FBLogPurchaseMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBLogPurchaseMessageRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    int getEventParameterCount();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    boolean containsEventParameter(
        java.lang.String key);
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameter();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameterMap();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */

    /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */

    java.lang.String getEventParameterOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code FBLogPurchaseMessageRequest}
   */
  public  static final class FBLogPurchaseMessageRequest extends
      com.google.protobuf.GeneratedMessageLite<
          FBLogPurchaseMessageRequest, FBLogPurchaseMessageRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:FBLogPurchaseMessageRequest)
      FBLogPurchaseMessageRequestOrBuilder {
    private FBLogPurchaseMessageRequest() {
      currency_ = "";
    }
    public static final int AMOUNT_FIELD_NUMBER = 1;
    private double amount_;
    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 1;</code>
     * @param value The amount to set.
     */
    private void setAmount(double value) {
      
      amount_ = value;
    }
    /**
     * <code>double amount = 1;</code>
     */
    private void clearAmount() {

      amount_ = 0D;
    }

    public static final int CURRENCY_FIELD_NUMBER = 2;
    private java.lang.String currency_;
    /**
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    @java.lang.Override
    public java.lang.String getCurrency() {
      return currency_;
    }
    /**
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(currency_);
    }
    /**
     * <code>string currency = 2;</code>
     * @param value The currency to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setCurrency(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      currency_ = value;
    }
    /**
     * <code>string currency = 2;</code>
     */
    private void clearCurrency() {

      currency_ = getDefaultInstance().getCurrency();
    }
    /**
     * <code>string currency = 2;</code>
     * @param value The bytes for currency to set.
     */
    private void setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      currency_ = value.toStringUtf8();

    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 3;
    private static final class EventParameterDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> eventParameter_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetEventParameter() {
      return eventParameter_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableEventParameter() {
      if (!eventParameter_.isMutable()) {
        eventParameter_ = eventParameter_.mutableCopy();
      }
      return eventParameter_;
    }
    @java.lang.Override

    public int getEventParameterCount() {
      return internalGetEventParameter().size();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override

    public boolean containsEventParameter(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return internalGetEventParameter().containsKey(key);
    }
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
      return getEventParameterMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetEventParameter());
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getEventParameterOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 3;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableEventParameterMap() {
      return internalGetMutableEventParameter();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code FBLogPurchaseMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:FBLogPurchaseMessageRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequestOrBuilder {
      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>double amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return instance.getAmount();
      }
      /**
       * <code>double amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <code>double amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <code>string currency = 2;</code>
       * @return The currency.
       */
      @java.lang.Override
      public java.lang.String getCurrency() {
        return instance.getCurrency();
      }
      /**
       * <code>string currency = 2;</code>
       * @return The bytes for currency.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        return instance.getCurrencyBytes();
      }
      /**
       * <code>string currency = 2;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          java.lang.String value) {
        copyOnWrite();
        instance.setCurrency(value);
        return this;
      }
      /**
       * <code>string currency = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        copyOnWrite();
        instance.clearCurrency();
        return this;
      }
      /**
       * <code>string currency = 2;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCurrencyBytes(value);
        return this;
      }

      @java.lang.Override

      public int getEventParameterCount() {
        return instance.getEventParameterMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override

      public boolean containsEventParameter(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        return instance.getEventParameterMap().containsKey(key);
      }

      public Builder clearEventParameter() {
        copyOnWrite();
        instance.getMutableEventParameterMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */

      public Builder removeEventParameter(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        copyOnWrite();
        instance.getMutableEventParameterMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getEventParameterMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
        return getEventParameterMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getEventParameterMap());
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override

      public /* nullable */
java.lang.String getEventParameterOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getEventParameterMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getEventParameterOrThrow(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getEventParameterMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      public Builder putEventParameter(
          java.lang.String key,
          java.lang.String value) {
        java.lang.Class<?> keyClass = key.getClass();
        java.lang.Class<?> valueClass = value.getClass();
        copyOnWrite();
        instance.getMutableEventParameterMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 3;</code>
       */
      public Builder putAllEventParameter(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableEventParameterMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBLogPurchaseMessageRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "amount_",
              "currency_",
              "eventParameter_",
              EventParameterDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0001\u0000\u0000\u0001\u0000\u0002\u0208" +
                "\u00032";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest> parser = PARSER;
          if (parser == null) {
            synchronized (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:FBLogPurchaseMessageRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest DEFAULT_INSTANCE;
    static {
      FBLogPurchaseMessageRequest defaultInstance = new FBLogPurchaseMessageRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FBLogPurchaseMessageRequest.class, defaultInstance);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogPurchaseMessage.FBLogPurchaseMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FBLogPurchaseMessageRequest> PARSER;

    public static com.google.protobuf.Parser<FBLogPurchaseMessageRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
