// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: log_standard_event_message.proto
// Protobuf Java Version: 4.29.3

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class LogStandardEventMessage {
  private LogStandardEventMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code FBStandardEvents}
   */
  public enum FBStandardEvents
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>AdClick = 0;</code>
     */
    AdClick(0),
    /**
     * <code>AdImpression = 1;</code>
     */
    AdImpression(1),
    /**
     * <code>CompletedRegistration = 2;</code>
     */
    CompletedRegistration(2),
    /**
     * <code>CompletedTutorial = 3;</code>
     */
    CompletedTutorial(3),
    /**
     * <code>Contact = 4;</code>
     */
    Contact(4),
    /**
     * <code>CustomizeProduct = 5;</code>
     */
    CustomizeProduct(5),
    /**
     * <code>Donate = 6;</code>
     */
    Donate(6),
    /**
     * <code>FindLocation = 7;</code>
     */
    FindLocation(7),
    /**
     * <code>Rated = 8;</code>
     */
    Rated(8),
    /**
     * <code>Schedule = 9;</code>
     */
    Schedule(9),
    /**
     * <code>Searched = 10;</code>
     */
    Searched(10),
    /**
     * <code>StartTrial = 11;</code>
     */
    StartTrial(11),
    /**
     * <code>SubmitApplication = 12;</code>
     */
    SubmitApplication(12),
    /**
     * <code>Subscribe = 13;</code>
     */
    Subscribe(13),
    /**
     * <code>ViewedContent = 14;</code>
     */
    ViewedContent(14),
    /**
     * <code>AddedPaymentInfo = 15;</code>
     */
    AddedPaymentInfo(15),
    /**
     * <code>AddedToCart = 16;</code>
     */
    AddedToCart(16),
    /**
     * <code>AddedToWishlist = 17;</code>
     */
    AddedToWishlist(17),
    /**
     * <code>InitiatedCheckout = 18;</code>
     */
    InitiatedCheckout(18),
    /**
     * <code>Purchased = 19;</code>
     */
    Purchased(19),
    /**
     * <code>AchievedLevel = 20;</code>
     */
    AchievedLevel(20),
    /**
     * <code>UnlockedAchievement = 21;</code>
     */
    UnlockedAchievement(21),
    /**
     * <code>SpentCredits = 22;</code>
     */
    SpentCredits(22),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AdClick = 0;</code>
     */
    public static final int AdClick_VALUE = 0;
    /**
     * <code>AdImpression = 1;</code>
     */
    public static final int AdImpression_VALUE = 1;
    /**
     * <code>CompletedRegistration = 2;</code>
     */
    public static final int CompletedRegistration_VALUE = 2;
    /**
     * <code>CompletedTutorial = 3;</code>
     */
    public static final int CompletedTutorial_VALUE = 3;
    /**
     * <code>Contact = 4;</code>
     */
    public static final int Contact_VALUE = 4;
    /**
     * <code>CustomizeProduct = 5;</code>
     */
    public static final int CustomizeProduct_VALUE = 5;
    /**
     * <code>Donate = 6;</code>
     */
    public static final int Donate_VALUE = 6;
    /**
     * <code>FindLocation = 7;</code>
     */
    public static final int FindLocation_VALUE = 7;
    /**
     * <code>Rated = 8;</code>
     */
    public static final int Rated_VALUE = 8;
    /**
     * <code>Schedule = 9;</code>
     */
    public static final int Schedule_VALUE = 9;
    /**
     * <code>Searched = 10;</code>
     */
    public static final int Searched_VALUE = 10;
    /**
     * <code>StartTrial = 11;</code>
     */
    public static final int StartTrial_VALUE = 11;
    /**
     * <code>SubmitApplication = 12;</code>
     */
    public static final int SubmitApplication_VALUE = 12;
    /**
     * <code>Subscribe = 13;</code>
     */
    public static final int Subscribe_VALUE = 13;
    /**
     * <code>ViewedContent = 14;</code>
     */
    public static final int ViewedContent_VALUE = 14;
    /**
     * <code>AddedPaymentInfo = 15;</code>
     */
    public static final int AddedPaymentInfo_VALUE = 15;
    /**
     * <code>AddedToCart = 16;</code>
     */
    public static final int AddedToCart_VALUE = 16;
    /**
     * <code>AddedToWishlist = 17;</code>
     */
    public static final int AddedToWishlist_VALUE = 17;
    /**
     * <code>InitiatedCheckout = 18;</code>
     */
    public static final int InitiatedCheckout_VALUE = 18;
    /**
     * <code>Purchased = 19;</code>
     */
    public static final int Purchased_VALUE = 19;
    /**
     * <code>AchievedLevel = 20;</code>
     */
    public static final int AchievedLevel_VALUE = 20;
    /**
     * <code>UnlockedAchievement = 21;</code>
     */
    public static final int UnlockedAchievement_VALUE = 21;
    /**
     * <code>SpentCredits = 22;</code>
     */
    public static final int SpentCredits_VALUE = 22;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FBStandardEvents valueOf(int value) {
      return forNumber(value);
    }

    public static FBStandardEvents forNumber(int value) {
      switch (value) {
        case 0: return AdClick;
        case 1: return AdImpression;
        case 2: return CompletedRegistration;
        case 3: return CompletedTutorial;
        case 4: return Contact;
        case 5: return CustomizeProduct;
        case 6: return Donate;
        case 7: return FindLocation;
        case 8: return Rated;
        case 9: return Schedule;
        case 10: return Searched;
        case 11: return StartTrial;
        case 12: return SubmitApplication;
        case 13: return Subscribe;
        case 14: return ViewedContent;
        case 15: return AddedPaymentInfo;
        case 16: return AddedToCart;
        case 17: return AddedToWishlist;
        case 18: return InitiatedCheckout;
        case 19: return Purchased;
        case 20: return AchievedLevel;
        case 21: return UnlockedAchievement;
        case 22: return SpentCredits;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FBStandardEvents>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FBStandardEvents> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FBStandardEvents>() {
            @java.lang.Override
            public FBStandardEvents findValueByNumber(int number) {
              return FBStandardEvents.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return FBStandardEventsVerifier.INSTANCE;
    }

    private static final class FBStandardEventsVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new FBStandardEventsVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return FBStandardEvents.forNumber(number) != null;
            }
          };

    private final int value;

    private FBStandardEvents(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FBStandardEvents)
  }

  /**
   * Protobuf enum {@code FBStandardParameters}
   */
  public enum FBStandardParameters
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ParameterNameContent = 0;</code>
     */
    ParameterNameContent(0),
    /**
     * <code>ParameterNameContentID = 1;</code>
     */
    ParameterNameContentID(1),
    /**
     * <code>ParameterNameContentType = 2;</code>
     */
    ParameterNameContentType(2),
    /**
     * <code>ParameterNameCurrency = 3;</code>
     */
    ParameterNameCurrency(3),
    /**
     * <code>ParameterNameDescription = 4;</code>
     */
    ParameterNameDescription(4),
    /**
     * <code>ParameterNameLevel = 5;</code>
     */
    ParameterNameLevel(5),
    /**
     * <code>ParameterNameMaxRatingValue = 6;</code>
     */
    ParameterNameMaxRatingValue(6),
    /**
     * <code>ParameterNameNumItems = 7;</code>
     */
    ParameterNameNumItems(7),
    /**
     * <code>ParameterNamePaymentInfoAvailable = 8;</code>
     */
    ParameterNamePaymentInfoAvailable(8),
    /**
     * <code>ParameterNameRegistrationMethod = 9;</code>
     */
    ParameterNameRegistrationMethod(9),
    /**
     * <code>ParameterNameSearchString = 10;</code>
     */
    ParameterNameSearchString(10),
    /**
     * <code>ParameterNameSuccess = 11;</code>
     */
    ParameterNameSuccess(11),
    /**
     * <code>ParameterNameAdType = 12;</code>
     */
    ParameterNameAdType(12),
    /**
     * <code>ParameterNameOrderID = 13;</code>
     */
    ParameterNameOrderID(13),
    /**
     * <code>ParameterNameEventName = 14;</code>
     */
    ParameterNameEventName(14),
    /**
     * <code>ParameterNameLogTime = 15;</code>
     */
    ParameterNameLogTime(15),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ParameterNameContent = 0;</code>
     */
    public static final int ParameterNameContent_VALUE = 0;
    /**
     * <code>ParameterNameContentID = 1;</code>
     */
    public static final int ParameterNameContentID_VALUE = 1;
    /**
     * <code>ParameterNameContentType = 2;</code>
     */
    public static final int ParameterNameContentType_VALUE = 2;
    /**
     * <code>ParameterNameCurrency = 3;</code>
     */
    public static final int ParameterNameCurrency_VALUE = 3;
    /**
     * <code>ParameterNameDescription = 4;</code>
     */
    public static final int ParameterNameDescription_VALUE = 4;
    /**
     * <code>ParameterNameLevel = 5;</code>
     */
    public static final int ParameterNameLevel_VALUE = 5;
    /**
     * <code>ParameterNameMaxRatingValue = 6;</code>
     */
    public static final int ParameterNameMaxRatingValue_VALUE = 6;
    /**
     * <code>ParameterNameNumItems = 7;</code>
     */
    public static final int ParameterNameNumItems_VALUE = 7;
    /**
     * <code>ParameterNamePaymentInfoAvailable = 8;</code>
     */
    public static final int ParameterNamePaymentInfoAvailable_VALUE = 8;
    /**
     * <code>ParameterNameRegistrationMethod = 9;</code>
     */
    public static final int ParameterNameRegistrationMethod_VALUE = 9;
    /**
     * <code>ParameterNameSearchString = 10;</code>
     */
    public static final int ParameterNameSearchString_VALUE = 10;
    /**
     * <code>ParameterNameSuccess = 11;</code>
     */
    public static final int ParameterNameSuccess_VALUE = 11;
    /**
     * <code>ParameterNameAdType = 12;</code>
     */
    public static final int ParameterNameAdType_VALUE = 12;
    /**
     * <code>ParameterNameOrderID = 13;</code>
     */
    public static final int ParameterNameOrderID_VALUE = 13;
    /**
     * <code>ParameterNameEventName = 14;</code>
     */
    public static final int ParameterNameEventName_VALUE = 14;
    /**
     * <code>ParameterNameLogTime = 15;</code>
     */
    public static final int ParameterNameLogTime_VALUE = 15;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FBStandardParameters valueOf(int value) {
      return forNumber(value);
    }

    public static FBStandardParameters forNumber(int value) {
      switch (value) {
        case 0: return ParameterNameContent;
        case 1: return ParameterNameContentID;
        case 2: return ParameterNameContentType;
        case 3: return ParameterNameCurrency;
        case 4: return ParameterNameDescription;
        case 5: return ParameterNameLevel;
        case 6: return ParameterNameMaxRatingValue;
        case 7: return ParameterNameNumItems;
        case 8: return ParameterNamePaymentInfoAvailable;
        case 9: return ParameterNameRegistrationMethod;
        case 10: return ParameterNameSearchString;
        case 11: return ParameterNameSuccess;
        case 12: return ParameterNameAdType;
        case 13: return ParameterNameOrderID;
        case 14: return ParameterNameEventName;
        case 15: return ParameterNameLogTime;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FBStandardParameters>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FBStandardParameters> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FBStandardParameters>() {
            @java.lang.Override
            public FBStandardParameters findValueByNumber(int number) {
              return FBStandardParameters.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return FBStandardParametersVerifier.INSTANCE;
    }

    private static final class FBStandardParametersVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new FBStandardParametersVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return FBStandardParameters.forNumber(number) != null;
            }
          };

    private final int value;

    private FBStandardParameters(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FBStandardParameters)
  }

  public interface FBLogStandardEventMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBLogStandardEventMessageRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The enum numeric value on the wire for eventName.
     */
    int getEventNameValue();
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The eventName.
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents getEventName();

    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> 
        getEventParameterList();
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getEventParameter(int index);
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    int getEventParameterCount();
  }
  /**
   * Protobuf type {@code FBLogStandardEventMessageRequest}
   */
  public  static final class FBLogStandardEventMessageRequest extends
      com.google.protobuf.GeneratedMessageLite<
          FBLogStandardEventMessageRequest, FBLogStandardEventMessageRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:FBLogStandardEventMessageRequest)
      FBLogStandardEventMessageRequestOrBuilder {
    private FBLogStandardEventMessageRequest() {
      eventParameter_ = emptyProtobufList();
    }
    public static final int EVENTNAME_FIELD_NUMBER = 1;
    private int eventName_;
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The enum numeric value on the wire for eventName.
     */
    @java.lang.Override
    public int getEventNameValue() {
      return eventName_;
    }
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The eventName.
     */
    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents getEventName() {
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.forNumber(eventName_);
      return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.UNRECOGNIZED : result;
    }
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @param value The enum numeric value on the wire for eventName to set.
     */
    private void setEventNameValue(int value) {
        eventName_ = value;
    }
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @param value The eventName to set.
     */
    private void setEventName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents value) {
      eventName_ = value.getNumber();

    }
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     */
    private void clearEventName() {

      eventName_ = 0;
    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> eventParameter_;
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> getEventParameterList() {
      return eventParameter_;
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    public java.util.List<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder> 
        getEventParameterOrBuilderList() {
      return eventParameter_;
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public int getEventParameterCount() {
      return eventParameter_.size();
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getEventParameter(int index) {
      return eventParameter_.get(index);
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder getEventParameterOrBuilder(
        int index) {
      return eventParameter_.get(index);
    }
    private void ensureEventParameterIsMutable() {
      com.google.protobuf.Internal.ProtobufList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> tmp = eventParameter_;
      if (!tmp.isModifiable()) {
        eventParameter_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setEventParameter(
        int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
      value.getClass();  // minimal bytecode null check
      ensureEventParameterIsMutable();
      eventParameter_.set(index, value);
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addEventParameter(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
      value.getClass();  // minimal bytecode null check
      ensureEventParameterIsMutable();
      eventParameter_.add(value);
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addEventParameter(
        int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
      value.getClass();  // minimal bytecode null check
      ensureEventParameterIsMutable();
      eventParameter_.add(index, value);
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    private void addAllEventParameter(
        java.lang.Iterable<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> values) {
      ensureEventParameterIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, eventParameter_);
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    private void clearEventParameter() {
      eventParameter_ = emptyProtobufList();
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    private void removeEventParameter(int index) {
      ensureEventParameterIsMutable();
      eventParameter_.remove(index);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code FBLogStandardEventMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:FBLogStandardEventMessageRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequestOrBuilder {
      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return The enum numeric value on the wire for eventName.
       */
      @java.lang.Override
      public int getEventNameValue() {
        return instance.getEventNameValue();
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameValue(int value) {
        copyOnWrite();
        instance.setEventNameValue(value);
        return this;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return The eventName.
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents getEventName() {
        return instance.getEventName();
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @param value The enum numeric value on the wire for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents value) {
        copyOnWrite();
        instance.setEventName(value);
        return this;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        copyOnWrite();
        instance.clearEventName();
        return this;
      }

      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      @java.lang.Override
      public java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> getEventParameterList() {
        return java.util.Collections.unmodifiableList(
            instance.getEventParameterList());
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      @java.lang.Override
      public int getEventParameterCount() {
        return instance.getEventParameterCount();
      }/**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getEventParameter(int index) {
        return instance.getEventParameter(index);
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder setEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
        copyOnWrite();
        instance.setEventParameter(index, value);
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder setEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder builderForValue) {
        copyOnWrite();
        instance.setEventParameter(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
        copyOnWrite();
        instance.addEventParameter(value);
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
        copyOnWrite();
        instance.addEventParameter(index, value);
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder builderForValue) {
        copyOnWrite();
        instance.addEventParameter(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder builderForValue) {
        copyOnWrite();
        instance.addEventParameter(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addAllEventParameter(
          java.lang.Iterable<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> values) {
        copyOnWrite();
        instance.addAllEventParameter(values);
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder clearEventParameter() {
        copyOnWrite();
        instance.clearEventParameter();
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder removeEventParameter(int index) {
        copyOnWrite();
        instance.removeEventParameter(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBLogStandardEventMessageRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "eventName_",
              "eventParameter_",
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\f\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest> parser = PARSER;
          if (parser == null) {
            synchronized (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:FBLogStandardEventMessageRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest DEFAULT_INSTANCE;
    static {
      FBLogStandardEventMessageRequest defaultInstance = new FBLogStandardEventMessageRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FBLogStandardEventMessageRequest.class, defaultInstance);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FBLogStandardEventMessageRequest> PARSER;

    public static com.google.protobuf.Parser<FBLogStandardEventMessageRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FBDefaultParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBDefaultParameter)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The enum numeric value on the wire for parameterName.
     */
    int getParameterNameValue();
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The parameterName.
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters getParameterName();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code FBDefaultParameter}
   */
  public  static final class FBDefaultParameter extends
      com.google.protobuf.GeneratedMessageLite<
          FBDefaultParameter, FBDefaultParameter.Builder> implements
      // @@protoc_insertion_point(message_implements:FBDefaultParameter)
      FBDefaultParameterOrBuilder {
    private FBDefaultParameter() {
      value_ = "";
    }
    public static final int PARAMETERNAME_FIELD_NUMBER = 1;
    private int parameterName_;
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The enum numeric value on the wire for parameterName.
     */
    @java.lang.Override
    public int getParameterNameValue() {
      return parameterName_;
    }
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The parameterName.
     */
    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters getParameterName() {
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.forNumber(parameterName_);
      return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.UNRECOGNIZED : result;
    }
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @param value The enum numeric value on the wire for parameterName to set.
     */
    private void setParameterNameValue(int value) {
        parameterName_ = value;
    }
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @param value The parameterName to set.
     */
    private void setParameterName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters value) {
      parameterName_ = value.getNumber();

    }
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     */
    private void clearParameterName() {

      parameterName_ = 0;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.String value_;
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string value = 2;</code>
     * @param value The value to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      value_ = value;
    }
    /**
     * <code>string value = 2;</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string value = 2;</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code FBDefaultParameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, Builder> implements
        // @@protoc_insertion_point(builder_implements:FBDefaultParameter)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder {
      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @return The enum numeric value on the wire for parameterName.
       */
      @java.lang.Override
      public int getParameterNameValue() {
        return instance.getParameterNameValue();
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @param value The parameterName to set.
       * @return This builder for chaining.
       */
      public Builder setParameterNameValue(int value) {
        copyOnWrite();
        instance.setParameterNameValue(value);
        return this;
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @return The parameterName.
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters getParameterName() {
        return instance.getParameterName();
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @param value The enum numeric value on the wire for parameterName to set.
       * @return This builder for chaining.
       */
      public Builder setParameterName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters value) {
        copyOnWrite();
        instance.setParameterName(value);
        return this;
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameterName() {
        copyOnWrite();
        instance.clearParameterName();
        return this;
      }

      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBDefaultParameter)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "parameterName_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> parser = PARSER;
          if (parser == null) {
            synchronized (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:FBDefaultParameter)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter DEFAULT_INSTANCE;
    static {
      FBDefaultParameter defaultInstance = new FBDefaultParameter();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FBDefaultParameter.class, defaultInstance);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FBDefaultParameter> PARSER;

    public static com.google.protobuf.Parser<FBDefaultParameter> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
