// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_standard_event_message.proto
// Protobuf Java Version: 4.26.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class LogStandardEventMessage {
  private LogStandardEventMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      LogStandardEventMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code FBStandardEvents}
   */
  public enum FBStandardEvents
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AdClick = 0;</code>
     */
    AdClick(0),
    /**
     * <code>AdImpression = 1;</code>
     */
    AdImpression(1),
    /**
     * <code>CompletedRegistration = 2;</code>
     */
    CompletedRegistration(2),
    /**
     * <code>CompletedTutorial = 3;</code>
     */
    CompletedTutorial(3),
    /**
     * <code>Contact = 4;</code>
     */
    Contact(4),
    /**
     * <code>CustomizeProduct = 5;</code>
     */
    CustomizeProduct(5),
    /**
     * <code>Donate = 6;</code>
     */
    Donate(6),
    /**
     * <code>FindLocation = 7;</code>
     */
    FindLocation(7),
    /**
     * <code>Rated = 8;</code>
     */
    Rated(8),
    /**
     * <code>Schedule = 9;</code>
     */
    Schedule(9),
    /**
     * <code>Searched = 10;</code>
     */
    Searched(10),
    /**
     * <code>StartTrial = 11;</code>
     */
    StartTrial(11),
    /**
     * <code>SubmitApplication = 12;</code>
     */
    SubmitApplication(12),
    /**
     * <code>Subscribe = 13;</code>
     */
    Subscribe(13),
    /**
     * <code>ViewedContent = 14;</code>
     */
    ViewedContent(14),
    /**
     * <code>AddedPaymentInfo = 15;</code>
     */
    AddedPaymentInfo(15),
    /**
     * <code>AddedToCart = 16;</code>
     */
    AddedToCart(16),
    /**
     * <code>AddedToWishlist = 17;</code>
     */
    AddedToWishlist(17),
    /**
     * <code>InitiatedCheckout = 18;</code>
     */
    InitiatedCheckout(18),
    /**
     * <code>Purchased = 19;</code>
     */
    Purchased(19),
    /**
     * <code>AchievedLevel = 20;</code>
     */
    AchievedLevel(20),
    /**
     * <code>UnlockedAchievement = 21;</code>
     */
    UnlockedAchievement(21),
    /**
     * <code>SpentCredits = 22;</code>
     */
    SpentCredits(22),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBStandardEvents.class.getName());
    }
    /**
     * <code>AdClick = 0;</code>
     */
    public static final int AdClick_VALUE = 0;
    /**
     * <code>AdImpression = 1;</code>
     */
    public static final int AdImpression_VALUE = 1;
    /**
     * <code>CompletedRegistration = 2;</code>
     */
    public static final int CompletedRegistration_VALUE = 2;
    /**
     * <code>CompletedTutorial = 3;</code>
     */
    public static final int CompletedTutorial_VALUE = 3;
    /**
     * <code>Contact = 4;</code>
     */
    public static final int Contact_VALUE = 4;
    /**
     * <code>CustomizeProduct = 5;</code>
     */
    public static final int CustomizeProduct_VALUE = 5;
    /**
     * <code>Donate = 6;</code>
     */
    public static final int Donate_VALUE = 6;
    /**
     * <code>FindLocation = 7;</code>
     */
    public static final int FindLocation_VALUE = 7;
    /**
     * <code>Rated = 8;</code>
     */
    public static final int Rated_VALUE = 8;
    /**
     * <code>Schedule = 9;</code>
     */
    public static final int Schedule_VALUE = 9;
    /**
     * <code>Searched = 10;</code>
     */
    public static final int Searched_VALUE = 10;
    /**
     * <code>StartTrial = 11;</code>
     */
    public static final int StartTrial_VALUE = 11;
    /**
     * <code>SubmitApplication = 12;</code>
     */
    public static final int SubmitApplication_VALUE = 12;
    /**
     * <code>Subscribe = 13;</code>
     */
    public static final int Subscribe_VALUE = 13;
    /**
     * <code>ViewedContent = 14;</code>
     */
    public static final int ViewedContent_VALUE = 14;
    /**
     * <code>AddedPaymentInfo = 15;</code>
     */
    public static final int AddedPaymentInfo_VALUE = 15;
    /**
     * <code>AddedToCart = 16;</code>
     */
    public static final int AddedToCart_VALUE = 16;
    /**
     * <code>AddedToWishlist = 17;</code>
     */
    public static final int AddedToWishlist_VALUE = 17;
    /**
     * <code>InitiatedCheckout = 18;</code>
     */
    public static final int InitiatedCheckout_VALUE = 18;
    /**
     * <code>Purchased = 19;</code>
     */
    public static final int Purchased_VALUE = 19;
    /**
     * <code>AchievedLevel = 20;</code>
     */
    public static final int AchievedLevel_VALUE = 20;
    /**
     * <code>UnlockedAchievement = 21;</code>
     */
    public static final int UnlockedAchievement_VALUE = 21;
    /**
     * <code>SpentCredits = 22;</code>
     */
    public static final int SpentCredits_VALUE = 22;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FBStandardEvents valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FBStandardEvents forNumber(int value) {
      switch (value) {
        case 0: return AdClick;
        case 1: return AdImpression;
        case 2: return CompletedRegistration;
        case 3: return CompletedTutorial;
        case 4: return Contact;
        case 5: return CustomizeProduct;
        case 6: return Donate;
        case 7: return FindLocation;
        case 8: return Rated;
        case 9: return Schedule;
        case 10: return Searched;
        case 11: return StartTrial;
        case 12: return SubmitApplication;
        case 13: return Subscribe;
        case 14: return ViewedContent;
        case 15: return AddedPaymentInfo;
        case 16: return AddedToCart;
        case 17: return AddedToWishlist;
        case 18: return InitiatedCheckout;
        case 19: return Purchased;
        case 20: return AchievedLevel;
        case 21: return UnlockedAchievement;
        case 22: return SpentCredits;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FBStandardEvents>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FBStandardEvents> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FBStandardEvents>() {
            public FBStandardEvents findValueByNumber(int number) {
              return FBStandardEvents.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final FBStandardEvents[] VALUES = values();

    public static FBStandardEvents valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FBStandardEvents(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FBStandardEvents)
  }

  /**
   * Protobuf enum {@code FBStandardParameters}
   */
  public enum FBStandardParameters
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ParameterNameContent = 0;</code>
     */
    ParameterNameContent(0),
    /**
     * <code>ParameterNameContentID = 1;</code>
     */
    ParameterNameContentID(1),
    /**
     * <code>ParameterNameContentType = 2;</code>
     */
    ParameterNameContentType(2),
    /**
     * <code>ParameterNameCurrency = 3;</code>
     */
    ParameterNameCurrency(3),
    /**
     * <code>ParameterNameDescription = 4;</code>
     */
    ParameterNameDescription(4),
    /**
     * <code>ParameterNameLevel = 5;</code>
     */
    ParameterNameLevel(5),
    /**
     * <code>ParameterNameMaxRatingValue = 6;</code>
     */
    ParameterNameMaxRatingValue(6),
    /**
     * <code>ParameterNameNumItems = 7;</code>
     */
    ParameterNameNumItems(7),
    /**
     * <code>ParameterNamePaymentInfoAvailable = 8;</code>
     */
    ParameterNamePaymentInfoAvailable(8),
    /**
     * <code>ParameterNameRegistrationMethod = 9;</code>
     */
    ParameterNameRegistrationMethod(9),
    /**
     * <code>ParameterNameSearchString = 10;</code>
     */
    ParameterNameSearchString(10),
    /**
     * <code>ParameterNameSuccess = 11;</code>
     */
    ParameterNameSuccess(11),
    /**
     * <code>ParameterNameAdType = 12;</code>
     */
    ParameterNameAdType(12),
    /**
     * <code>ParameterNameOrderID = 13;</code>
     */
    ParameterNameOrderID(13),
    /**
     * <code>ParameterNameEventName = 14;</code>
     */
    ParameterNameEventName(14),
    /**
     * <code>ParameterNameLogTime = 15;</code>
     */
    ParameterNameLogTime(15),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBStandardParameters.class.getName());
    }
    /**
     * <code>ParameterNameContent = 0;</code>
     */
    public static final int ParameterNameContent_VALUE = 0;
    /**
     * <code>ParameterNameContentID = 1;</code>
     */
    public static final int ParameterNameContentID_VALUE = 1;
    /**
     * <code>ParameterNameContentType = 2;</code>
     */
    public static final int ParameterNameContentType_VALUE = 2;
    /**
     * <code>ParameterNameCurrency = 3;</code>
     */
    public static final int ParameterNameCurrency_VALUE = 3;
    /**
     * <code>ParameterNameDescription = 4;</code>
     */
    public static final int ParameterNameDescription_VALUE = 4;
    /**
     * <code>ParameterNameLevel = 5;</code>
     */
    public static final int ParameterNameLevel_VALUE = 5;
    /**
     * <code>ParameterNameMaxRatingValue = 6;</code>
     */
    public static final int ParameterNameMaxRatingValue_VALUE = 6;
    /**
     * <code>ParameterNameNumItems = 7;</code>
     */
    public static final int ParameterNameNumItems_VALUE = 7;
    /**
     * <code>ParameterNamePaymentInfoAvailable = 8;</code>
     */
    public static final int ParameterNamePaymentInfoAvailable_VALUE = 8;
    /**
     * <code>ParameterNameRegistrationMethod = 9;</code>
     */
    public static final int ParameterNameRegistrationMethod_VALUE = 9;
    /**
     * <code>ParameterNameSearchString = 10;</code>
     */
    public static final int ParameterNameSearchString_VALUE = 10;
    /**
     * <code>ParameterNameSuccess = 11;</code>
     */
    public static final int ParameterNameSuccess_VALUE = 11;
    /**
     * <code>ParameterNameAdType = 12;</code>
     */
    public static final int ParameterNameAdType_VALUE = 12;
    /**
     * <code>ParameterNameOrderID = 13;</code>
     */
    public static final int ParameterNameOrderID_VALUE = 13;
    /**
     * <code>ParameterNameEventName = 14;</code>
     */
    public static final int ParameterNameEventName_VALUE = 14;
    /**
     * <code>ParameterNameLogTime = 15;</code>
     */
    public static final int ParameterNameLogTime_VALUE = 15;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FBStandardParameters valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FBStandardParameters forNumber(int value) {
      switch (value) {
        case 0: return ParameterNameContent;
        case 1: return ParameterNameContentID;
        case 2: return ParameterNameContentType;
        case 3: return ParameterNameCurrency;
        case 4: return ParameterNameDescription;
        case 5: return ParameterNameLevel;
        case 6: return ParameterNameMaxRatingValue;
        case 7: return ParameterNameNumItems;
        case 8: return ParameterNamePaymentInfoAvailable;
        case 9: return ParameterNameRegistrationMethod;
        case 10: return ParameterNameSearchString;
        case 11: return ParameterNameSuccess;
        case 12: return ParameterNameAdType;
        case 13: return ParameterNameOrderID;
        case 14: return ParameterNameEventName;
        case 15: return ParameterNameLogTime;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FBStandardParameters>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FBStandardParameters> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FBStandardParameters>() {
            public FBStandardParameters findValueByNumber(int number) {
              return FBStandardParameters.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final FBStandardParameters[] VALUES = values();

    public static FBStandardParameters valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FBStandardParameters(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FBStandardParameters)
  }

  public interface FBLogStandardEventMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBLogStandardEventMessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The enum numeric value on the wire for eventName.
     */
    int getEventNameValue();
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The eventName.
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents getEventName();

    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> 
        getEventParameterList();
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getEventParameter(int index);
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    int getEventParameterCount();
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    java.util.List<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder> 
        getEventParameterOrBuilderList();
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder getEventParameterOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code FBLogStandardEventMessageRequest}
   */
  public static final class FBLogStandardEventMessageRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FBLogStandardEventMessageRequest)
      FBLogStandardEventMessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBLogStandardEventMessageRequest.class.getName());
    }
    // Use FBLogStandardEventMessageRequest.newBuilder() to construct.
    private FBLogStandardEventMessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FBLogStandardEventMessageRequest() {
      eventName_ = 0;
      eventParameter_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBLogStandardEventMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBLogStandardEventMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.Builder.class);
    }

    public static final int EVENTNAME_FIELD_NUMBER = 1;
    private int eventName_ = 0;
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The enum numeric value on the wire for eventName.
     */
    @java.lang.Override public int getEventNameValue() {
      return eventName_;
    }
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The eventName.
     */
    @java.lang.Override public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents getEventName() {
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.forNumber(eventName_);
      return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.UNRECOGNIZED : result;
    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> eventParameter_;
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> getEventParameterList() {
      return eventParameter_;
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder> 
        getEventParameterOrBuilderList() {
      return eventParameter_;
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public int getEventParameterCount() {
      return eventParameter_.size();
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getEventParameter(int index) {
      return eventParameter_.get(index);
    }
    /**
     * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
     */
    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder getEventParameterOrBuilder(
        int index) {
      return eventParameter_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventName_ != cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.AdClick.getNumber()) {
        output.writeEnum(1, eventName_);
      }
      for (int i = 0; i < eventParameter_.size(); i++) {
        output.writeMessage(2, eventParameter_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventName_ != cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.AdClick.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eventName_);
      }
      for (int i = 0; i < eventParameter_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, eventParameter_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest)) {
        return super.equals(obj);
      }
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest other = (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest) obj;

      if (eventName_ != other.eventName_) return false;
      if (!getEventParameterList()
          .equals(other.getEventParameterList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENTNAME_FIELD_NUMBER;
      hash = (53 * hash) + eventName_;
      if (getEventParameterCount() > 0) {
        hash = (37 * hash) + EVENTPARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + getEventParameterList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FBLogStandardEventMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FBLogStandardEventMessageRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBLogStandardEventMessageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBLogStandardEventMessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.Builder.class);
      }

      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        eventName_ = 0;
        if (eventParameterBuilder_ == null) {
          eventParameter_ = java.util.Collections.emptyList();
        } else {
          eventParameter_ = null;
          eventParameterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBLogStandardEventMessageRequest_descriptor;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest getDefaultInstanceForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest build() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest buildPartial() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest result = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest result) {
        if (eventParameterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            eventParameter_ = java.util.Collections.unmodifiableList(eventParameter_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.eventParameter_ = eventParameter_;
        } else {
          result.eventParameter_ = eventParameterBuilder_.build();
        }
      }

      private void buildPartial0(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.eventName_ = eventName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest) {
          return mergeFrom((cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest other) {
        if (other == cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest.getDefaultInstance()) return this;
        if (other.eventName_ != 0) {
          setEventNameValue(other.getEventNameValue());
        }
        if (eventParameterBuilder_ == null) {
          if (!other.eventParameter_.isEmpty()) {
            if (eventParameter_.isEmpty()) {
              eventParameter_ = other.eventParameter_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEventParameterIsMutable();
              eventParameter_.addAll(other.eventParameter_);
            }
            onChanged();
          }
        } else {
          if (!other.eventParameter_.isEmpty()) {
            if (eventParameterBuilder_.isEmpty()) {
              eventParameterBuilder_.dispose();
              eventParameterBuilder_ = null;
              eventParameter_ = other.eventParameter_;
              bitField0_ = (bitField0_ & ~0x00000002);
              eventParameterBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEventParameterFieldBuilder() : null;
            } else {
              eventParameterBuilder_.addAllMessages(other.eventParameter_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                eventName_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter m =
                    input.readMessage(
                        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.parser(),
                        extensionRegistry);
                if (eventParameterBuilder_ == null) {
                  ensureEventParameterIsMutable();
                  eventParameter_.add(m);
                } else {
                  eventParameterBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int eventName_ = 0;
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return The enum numeric value on the wire for eventName.
       */
      @java.lang.Override public int getEventNameValue() {
        return eventName_;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @param value The enum numeric value on the wire for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameValue(int value) {
        eventName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return The eventName.
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents getEventName() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.forNumber(eventName_);
        return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents.UNRECOGNIZED : result;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardEvents value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        eventName_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventName_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> eventParameter_ =
        java.util.Collections.emptyList();
      private void ensureEventParameterIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          eventParameter_ = new java.util.ArrayList<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter>(eventParameter_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder> eventParameterBuilder_;

      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> getEventParameterList() {
        if (eventParameterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(eventParameter_);
        } else {
          return eventParameterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public int getEventParameterCount() {
        if (eventParameterBuilder_ == null) {
          return eventParameter_.size();
        } else {
          return eventParameterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getEventParameter(int index) {
        if (eventParameterBuilder_ == null) {
          return eventParameter_.get(index);
        } else {
          return eventParameterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder setEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
        if (eventParameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventParameterIsMutable();
          eventParameter_.set(index, value);
          onChanged();
        } else {
          eventParameterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder setEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder builderForValue) {
        if (eventParameterBuilder_ == null) {
          ensureEventParameterIsMutable();
          eventParameter_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventParameterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
        if (eventParameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventParameterIsMutable();
          eventParameter_.add(value);
          onChanged();
        } else {
          eventParameterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter value) {
        if (eventParameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventParameterIsMutable();
          eventParameter_.add(index, value);
          onChanged();
        } else {
          eventParameterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder builderForValue) {
        if (eventParameterBuilder_ == null) {
          ensureEventParameterIsMutable();
          eventParameter_.add(builderForValue.build());
          onChanged();
        } else {
          eventParameterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addEventParameter(
          int index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder builderForValue) {
        if (eventParameterBuilder_ == null) {
          ensureEventParameterIsMutable();
          eventParameter_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventParameterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder addAllEventParameter(
          java.lang.Iterable<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter> values) {
        if (eventParameterBuilder_ == null) {
          ensureEventParameterIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, eventParameter_);
          onChanged();
        } else {
          eventParameterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder clearEventParameter() {
        if (eventParameterBuilder_ == null) {
          eventParameter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          eventParameterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public Builder removeEventParameter(int index) {
        if (eventParameterBuilder_ == null) {
          ensureEventParameterIsMutable();
          eventParameter_.remove(index);
          onChanged();
        } else {
          eventParameterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder getEventParameterBuilder(
          int index) {
        return getEventParameterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder getEventParameterOrBuilder(
          int index) {
        if (eventParameterBuilder_ == null) {
          return eventParameter_.get(index);  } else {
          return eventParameterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public java.util.List<? extends cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder> 
           getEventParameterOrBuilderList() {
        if (eventParameterBuilder_ != null) {
          return eventParameterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(eventParameter_);
        }
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder addEventParameterBuilder() {
        return getEventParameterFieldBuilder().addBuilder(
            cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder addEventParameterBuilder(
          int index) {
        return getEventParameterFieldBuilder().addBuilder(
            index, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .FBDefaultParameter eventParameter = 2;</code>
       */
      public java.util.List<cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder> 
           getEventParameterBuilderList() {
        return getEventParameterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder> 
          getEventParameterFieldBuilder() {
        if (eventParameterBuilder_ == null) {
          eventParameterBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder>(
                  eventParameter_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          eventParameter_ = null;
        }
        return eventParameterBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:FBLogStandardEventMessageRequest)
    }

    // @@protoc_insertion_point(class_scope:FBLogStandardEventMessageRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FBLogStandardEventMessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<FBLogStandardEventMessageRequest>() {
      @java.lang.Override
      public FBLogStandardEventMessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FBLogStandardEventMessageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FBLogStandardEventMessageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBLogStandardEventMessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FBDefaultParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBDefaultParameter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The enum numeric value on the wire for parameterName.
     */
    int getParameterNameValue();
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The parameterName.
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters getParameterName();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code FBDefaultParameter}
   */
  public static final class FBDefaultParameter extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FBDefaultParameter)
      FBDefaultParameterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBDefaultParameter.class.getName());
    }
    // Use FBDefaultParameter.newBuilder() to construct.
    private FBDefaultParameter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FBDefaultParameter() {
      parameterName_ = 0;
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBDefaultParameter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBDefaultParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder.class);
    }

    public static final int PARAMETERNAME_FIELD_NUMBER = 1;
    private int parameterName_ = 0;
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The enum numeric value on the wire for parameterName.
     */
    @java.lang.Override public int getParameterNameValue() {
      return parameterName_;
    }
    /**
     * <code>.FBStandardParameters parameterName = 1;</code>
     * @return The parameterName.
     */
    @java.lang.Override public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters getParameterName() {
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.forNumber(parameterName_);
      return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (parameterName_ != cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.ParameterNameContent.getNumber()) {
        output.writeEnum(1, parameterName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (parameterName_ != cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.ParameterNameContent.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, parameterName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter)) {
        return super.equals(obj);
      }
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter other = (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter) obj;

      if (parameterName_ != other.parameterName_) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PARAMETERNAME_FIELD_NUMBER;
      hash = (53 * hash) + parameterName_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FBDefaultParameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FBDefaultParameter)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBDefaultParameter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBDefaultParameter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.Builder.class);
      }

      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        parameterName_ = 0;
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.internal_static_FBDefaultParameter_descriptor;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getDefaultInstanceForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.getDefaultInstance();
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter build() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter buildPartial() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter result = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.parameterName_ = parameterName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter) {
          return mergeFrom((cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter other) {
        if (other == cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter.getDefaultInstance()) return this;
        if (other.parameterName_ != 0) {
          setParameterNameValue(other.getParameterNameValue());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                parameterName_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int parameterName_ = 0;
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @return The enum numeric value on the wire for parameterName.
       */
      @java.lang.Override public int getParameterNameValue() {
        return parameterName_;
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @param value The enum numeric value on the wire for parameterName to set.
       * @return This builder for chaining.
       */
      public Builder setParameterNameValue(int value) {
        parameterName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @return The parameterName.
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters getParameterName() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.forNumber(parameterName_);
        return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters.UNRECOGNIZED : result;
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @param value The parameterName to set.
       * @return This builder for chaining.
       */
      public Builder setParameterName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBStandardParameters value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        parameterName_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.FBStandardParameters parameterName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameterName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        parameterName_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBDefaultParameter)
    }

    // @@protoc_insertion_point(class_scope:FBDefaultParameter)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FBDefaultParameter>
        PARSER = new com.google.protobuf.AbstractParser<FBDefaultParameter>() {
      @java.lang.Override
      public FBDefaultParameter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FBDefaultParameter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FBDefaultParameter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessage.FBDefaultParameter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBLogStandardEventMessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBLogStandardEventMessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FBDefaultParameter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FBDefaultParameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n log_standard_event_message.proto\"u\n FB" +
      "LogStandardEventMessageRequest\022$\n\teventN" +
      "ame\030\001 \001(\0162\021.FBStandardEvents\022+\n\016eventPar" +
      "ameter\030\002 \003(\0132\023.FBDefaultParameter\"Q\n\022FBD" +
      "efaultParameter\022,\n\rparameterName\030\001 \001(\0162\025" +
      ".FBStandardParameters\022\r\n\005value\030\002 \001(\t*\264\003\n" +
      "\020FBStandardEvents\022\013\n\007AdClick\020\000\022\020\n\014AdImpr" +
      "ession\020\001\022\031\n\025CompletedRegistration\020\002\022\025\n\021C" +
      "ompletedTutorial\020\003\022\013\n\007Contact\020\004\022\024\n\020Custo" +
      "mizeProduct\020\005\022\n\n\006Donate\020\006\022\020\n\014FindLocatio" +
      "n\020\007\022\t\n\005Rated\020\010\022\014\n\010Schedule\020\t\022\014\n\010Searched" +
      "\020\n\022\016\n\nStartTrial\020\013\022\025\n\021SubmitApplication\020" +
      "\014\022\r\n\tSubscribe\020\r\022\021\n\rViewedContent\020\016\022\024\n\020A" +
      "ddedPaymentInfo\020\017\022\017\n\013AddedToCart\020\020\022\023\n\017Ad" +
      "dedToWishlist\020\021\022\025\n\021InitiatedCheckout\020\022\022\r" +
      "\n\tPurchased\020\023\022\021\n\rAchievedLevel\020\024\022\027\n\023Unlo" +
      "ckedAchievement\020\025\022\020\n\014SpentCredits\020\026*\345\003\n\024" +
      "FBStandardParameters\022\030\n\024ParameterNameCon" +
      "tent\020\000\022\032\n\026ParameterNameContentID\020\001\022\034\n\030Pa" +
      "rameterNameContentType\020\002\022\031\n\025ParameterNam" +
      "eCurrency\020\003\022\034\n\030ParameterNameDescription\020" +
      "\004\022\026\n\022ParameterNameLevel\020\005\022\037\n\033ParameterNa" +
      "meMaxRatingValue\020\006\022\031\n\025ParameterNameNumIt" +
      "ems\020\007\022%\n!ParameterNamePaymentInfoAvailab" +
      "le\020\010\022#\n\037ParameterNameRegistrationMethod\020" +
      "\t\022\035\n\031ParameterNameSearchString\020\n\022\030\n\024Para" +
      "meterNameSuccess\020\013\022\027\n\023ParameterNameAdTyp" +
      "e\020\014\022\030\n\024ParameterNameOrderID\020\r\022\032\n\026Paramet" +
      "erNameEventName\020\016\022\030\n\024ParameterNameLogTim" +
      "e\020\017B1\n/cat.durban.sergio.flutter_meta_ap" +
      "pads_sdk.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FBLogStandardEventMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FBLogStandardEventMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBLogStandardEventMessageRequest_descriptor,
        new java.lang.String[] { "EventName", "EventParameter", });
    internal_static_FBDefaultParameter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FBDefaultParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FBDefaultParameter_descriptor,
        new java.lang.String[] { "ParameterName", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
