// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_standard_event_message.proto
// Protobuf Java Version: 4.26.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

public final class LogStandardEventMessageOuterClass {
  private LogStandardEventMessageOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      LogStandardEventMessageOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code FBStandardEvents}
   */
  public enum FBStandardEvents
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AdClick = 0;</code>
     */
    AdClick(0),
    /**
     * <code>AdImpression = 1;</code>
     */
    AdImpression(1),
    /**
     * <code>CompletedRegistration = 2;</code>
     */
    CompletedRegistration(2),
    /**
     * <code>CompletedTutorial = 3;</code>
     */
    CompletedTutorial(3),
    /**
     * <code>Contact = 4;</code>
     */
    Contact(4),
    /**
     * <code>CustomizeProduct = 5;</code>
     */
    CustomizeProduct(5),
    /**
     * <code>Donate = 6;</code>
     */
    Donate(6),
    /**
     * <code>FindLocation = 7;</code>
     */
    FindLocation(7),
    /**
     * <code>Rated = 8;</code>
     */
    Rated(8),
    /**
     * <code>Schedule = 9;</code>
     */
    Schedule(9),
    /**
     * <code>Searched = 10;</code>
     */
    Searched(10),
    /**
     * <code>StartTrial = 11;</code>
     */
    StartTrial(11),
    /**
     * <code>SubmitApplication = 12;</code>
     */
    SubmitApplication(12),
    /**
     * <code>Subscribe = 13;</code>
     */
    Subscribe(13),
    /**
     * <code>ViewedContent = 14;</code>
     */
    ViewedContent(14),
    /**
     * <code>AddedPaymentInfo = 15;</code>
     */
    AddedPaymentInfo(15),
    /**
     * <code>AddedToCart = 16;</code>
     */
    AddedToCart(16),
    /**
     * <code>AddedToWishlist = 17;</code>
     */
    AddedToWishlist(17),
    /**
     * <code>InitiatedCheckout = 18;</code>
     */
    InitiatedCheckout(18),
    /**
     * <code>Purchased = 19;</code>
     */
    Purchased(19),
    /**
     * <code>AchievedLevel = 20;</code>
     */
    AchievedLevel(20),
    /**
     * <code>UnlockedAchievement = 21;</code>
     */
    UnlockedAchievement(21),
    /**
     * <code>SpentCredits = 22;</code>
     */
    SpentCredits(22),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        FBStandardEvents.class.getName());
    }
    /**
     * <code>AdClick = 0;</code>
     */
    public static final int AdClick_VALUE = 0;
    /**
     * <code>AdImpression = 1;</code>
     */
    public static final int AdImpression_VALUE = 1;
    /**
     * <code>CompletedRegistration = 2;</code>
     */
    public static final int CompletedRegistration_VALUE = 2;
    /**
     * <code>CompletedTutorial = 3;</code>
     */
    public static final int CompletedTutorial_VALUE = 3;
    /**
     * <code>Contact = 4;</code>
     */
    public static final int Contact_VALUE = 4;
    /**
     * <code>CustomizeProduct = 5;</code>
     */
    public static final int CustomizeProduct_VALUE = 5;
    /**
     * <code>Donate = 6;</code>
     */
    public static final int Donate_VALUE = 6;
    /**
     * <code>FindLocation = 7;</code>
     */
    public static final int FindLocation_VALUE = 7;
    /**
     * <code>Rated = 8;</code>
     */
    public static final int Rated_VALUE = 8;
    /**
     * <code>Schedule = 9;</code>
     */
    public static final int Schedule_VALUE = 9;
    /**
     * <code>Searched = 10;</code>
     */
    public static final int Searched_VALUE = 10;
    /**
     * <code>StartTrial = 11;</code>
     */
    public static final int StartTrial_VALUE = 11;
    /**
     * <code>SubmitApplication = 12;</code>
     */
    public static final int SubmitApplication_VALUE = 12;
    /**
     * <code>Subscribe = 13;</code>
     */
    public static final int Subscribe_VALUE = 13;
    /**
     * <code>ViewedContent = 14;</code>
     */
    public static final int ViewedContent_VALUE = 14;
    /**
     * <code>AddedPaymentInfo = 15;</code>
     */
    public static final int AddedPaymentInfo_VALUE = 15;
    /**
     * <code>AddedToCart = 16;</code>
     */
    public static final int AddedToCart_VALUE = 16;
    /**
     * <code>AddedToWishlist = 17;</code>
     */
    public static final int AddedToWishlist_VALUE = 17;
    /**
     * <code>InitiatedCheckout = 18;</code>
     */
    public static final int InitiatedCheckout_VALUE = 18;
    /**
     * <code>Purchased = 19;</code>
     */
    public static final int Purchased_VALUE = 19;
    /**
     * <code>AchievedLevel = 20;</code>
     */
    public static final int AchievedLevel_VALUE = 20;
    /**
     * <code>UnlockedAchievement = 21;</code>
     */
    public static final int UnlockedAchievement_VALUE = 21;
    /**
     * <code>SpentCredits = 22;</code>
     */
    public static final int SpentCredits_VALUE = 22;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FBStandardEvents valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FBStandardEvents forNumber(int value) {
      switch (value) {
        case 0: return AdClick;
        case 1: return AdImpression;
        case 2: return CompletedRegistration;
        case 3: return CompletedTutorial;
        case 4: return Contact;
        case 5: return CustomizeProduct;
        case 6: return Donate;
        case 7: return FindLocation;
        case 8: return Rated;
        case 9: return Schedule;
        case 10: return Searched;
        case 11: return StartTrial;
        case 12: return SubmitApplication;
        case 13: return Subscribe;
        case 14: return ViewedContent;
        case 15: return AddedPaymentInfo;
        case 16: return AddedToCart;
        case 17: return AddedToWishlist;
        case 18: return InitiatedCheckout;
        case 19: return Purchased;
        case 20: return AchievedLevel;
        case 21: return UnlockedAchievement;
        case 22: return SpentCredits;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FBStandardEvents>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FBStandardEvents> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FBStandardEvents>() {
            public FBStandardEvents findValueByNumber(int number) {
              return FBStandardEvents.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final FBStandardEvents[] VALUES = values();

    public static FBStandardEvents valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FBStandardEvents(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FBStandardEvents)
  }

  public interface LogStandardEventMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogStandardEventMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The enum numeric value on the wire for eventName.
     */
    int getEventNameValue();
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The eventName.
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents getEventName();

    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    int getEventParameterCount();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    boolean containsEventParameter(
        java.lang.String key);
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameter();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getEventParameterMap();
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    java.lang.String getEventParameterOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code LogStandardEventMessage}
   */
  public static final class LogStandardEventMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LogStandardEventMessage)
      LogStandardEventMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        LogStandardEventMessage.class.getName());
    }
    // Use LogStandardEventMessage.newBuilder() to construct.
    private LogStandardEventMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LogStandardEventMessage() {
      eventName_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.internal_static_LogStandardEventMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetEventParameter();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.internal_static_LogStandardEventMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.Builder.class);
    }

    public static final int EVENTNAME_FIELD_NUMBER = 1;
    private int eventName_ = 0;
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The enum numeric value on the wire for eventName.
     */
    @java.lang.Override public int getEventNameValue() {
      return eventName_;
    }
    /**
     * <code>.FBStandardEvents eventName = 1;</code>
     * @return The eventName.
     */
    @java.lang.Override public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents getEventName() {
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents.forNumber(eventName_);
      return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents.UNRECOGNIZED : result;
    }

    public static final int EVENTPARAMETER_FIELD_NUMBER = 2;
    private static final class EventParameterDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.internal_static_LogStandardEventMessage_EventParameterEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> eventParameter_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetEventParameter() {
      if (eventParameter_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventParameterDefaultEntryHolder.defaultEntry);
      }
      return eventParameter_;
    }
    public int getEventParameterCount() {
      return internalGetEventParameter().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public boolean containsEventParameter(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEventParameter().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventParameterMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
      return getEventParameterMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
      return internalGetEventParameter().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getEventParameterOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; eventParameter = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getEventParameterOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventParameter().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventName_ != cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents.AdClick.getNumber()) {
        output.writeEnum(1, eventName_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetEventParameter(),
          EventParameterDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventName_ != cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents.AdClick.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eventName_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetEventParameter().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        eventParameter__ = EventParameterDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, eventParameter__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage)) {
        return super.equals(obj);
      }
      cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage other = (cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage) obj;

      if (eventName_ != other.eventName_) return false;
      if (!internalGetEventParameter().equals(
          other.internalGetEventParameter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENTNAME_FIELD_NUMBER;
      hash = (53 * hash) + eventName_;
      if (!internalGetEventParameter().getMap().isEmpty()) {
        hash = (37 * hash) + EVENTPARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEventParameter().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogStandardEventMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogStandardEventMessage)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.internal_static_LogStandardEventMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetEventParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableEventParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.internal_static_LogStandardEventMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.class, cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.Builder.class);
      }

      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        eventName_ = 0;
        internalGetMutableEventParameter().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.internal_static_LogStandardEventMessage_descriptor;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage getDefaultInstanceForType() {
        return cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.getDefaultInstance();
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage build() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage buildPartial() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage result = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.eventName_ = eventName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.eventParameter_ = internalGetEventParameter();
          result.eventParameter_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage) {
          return mergeFrom((cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage other) {
        if (other == cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage.getDefaultInstance()) return this;
        if (other.eventName_ != 0) {
          setEventNameValue(other.getEventNameValue());
        }
        internalGetMutableEventParameter().mergeFrom(
            other.internalGetEventParameter());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                eventName_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                eventParameter__ = input.readMessage(
                    EventParameterDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableEventParameter().getMutableMap().put(
                    eventParameter__.getKey(), eventParameter__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int eventName_ = 0;
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return The enum numeric value on the wire for eventName.
       */
      @java.lang.Override public int getEventNameValue() {
        return eventName_;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @param value The enum numeric value on the wire for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameValue(int value) {
        eventName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return The eventName.
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents getEventName() {
        cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents result = cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents.forNumber(eventName_);
        return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents.UNRECOGNIZED : result;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.FBStandardEvents value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        eventName_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.FBStandardEvents eventName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventName_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> eventParameter_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetEventParameter() {
        if (eventParameter_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EventParameterDefaultEntryHolder.defaultEntry);
        }
        return eventParameter_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableEventParameter() {
        if (eventParameter_ == null) {
          eventParameter_ = com.google.protobuf.MapField.newMapField(
              EventParameterDefaultEntryHolder.defaultEntry);
        }
        if (!eventParameter_.isMutable()) {
          eventParameter_ = eventParameter_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return eventParameter_;
      }
      public int getEventParameterCount() {
        return internalGetEventParameter().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public boolean containsEventParameter(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetEventParameter().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEventParameterMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getEventParameter() {
        return getEventParameterMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getEventParameterMap() {
        return internalGetEventParameter().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getEventParameterOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetEventParameter().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getEventParameterOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetEventParameter().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearEventParameter() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableEventParameter().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder removeEventParameter(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableEventParameter().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableEventParameter() {
        bitField0_ |= 0x00000002;
        return internalGetMutableEventParameter().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder putEventParameter(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableEventParameter().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; eventParameter = 2;</code>
       */
      public Builder putAllEventParameter(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableEventParameter().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LogStandardEventMessage)
    }

    // @@protoc_insertion_point(class_scope:LogStandardEventMessage)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage();
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogStandardEventMessage>
        PARSER = new com.google.protobuf.AbstractParser<LogStandardEventMessage>() {
      @java.lang.Override
      public LogStandardEventMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogStandardEventMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogStandardEventMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.LogStandardEventMessageOuterClass.LogStandardEventMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogStandardEventMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LogStandardEventMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogStandardEventMessage_EventParameterEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LogStandardEventMessage_EventParameterEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n log_standard_event_message.proto\"\274\001\n\027L" +
      "ogStandardEventMessage\022$\n\teventName\030\001 \001(" +
      "\0162\021.FBStandardEvents\022D\n\016eventParameter\030\002" +
      " \003(\0132,.LogStandardEventMessage.EventPara" +
      "meterEntry\0325\n\023EventParameterEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*\264\003\n\020FBStandard" +
      "Events\022\013\n\007AdClick\020\000\022\020\n\014AdImpression\020\001\022\031\n" +
      "\025CompletedRegistration\020\002\022\025\n\021CompletedTut" +
      "orial\020\003\022\013\n\007Contact\020\004\022\024\n\020CustomizeProduct" +
      "\020\005\022\n\n\006Donate\020\006\022\020\n\014FindLocation\020\007\022\t\n\005Rate" +
      "d\020\010\022\014\n\010Schedule\020\t\022\014\n\010Searched\020\n\022\016\n\nStart" +
      "Trial\020\013\022\025\n\021SubmitApplication\020\014\022\r\n\tSubscr" +
      "ibe\020\r\022\021\n\rViewedContent\020\016\022\024\n\020AddedPayment" +
      "Info\020\017\022\017\n\013AddedToCart\020\020\022\023\n\017AddedToWishli" +
      "st\020\021\022\025\n\021InitiatedCheckout\020\022\022\r\n\tPurchased" +
      "\020\023\022\021\n\rAchievedLevel\020\024\022\027\n\023UnlockedAchieve" +
      "ment\020\025\022\020\n\014SpentCredits\020\026B1\n/cat.durban.s" +
      "ergio.flutter_meta_appads_sdk.protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LogStandardEventMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogStandardEventMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LogStandardEventMessage_descriptor,
        new java.lang.String[] { "EventName", "EventParameter", });
    internal_static_LogStandardEventMessage_EventParameterEntry_descriptor =
      internal_static_LogStandardEventMessage_descriptor.getNestedTypes().get(0);
    internal_static_LogStandardEventMessage_EventParameterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LogStandardEventMessage_EventParameterEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
