// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: set_user_data_message.proto
// Protobuf Java Version: 4.32.1

package cat.durban.sergio.flutter_meta_appads_sdk.proto;

@com.google.protobuf.Generated
public final class SetUserDataMessage {
  private SetUserDataMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code FBUserDataType}
   */
  public enum FBUserDataType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Email = 0;</code>
     */
    Email(0),
    /**
     * <code>FirstName = 1;</code>
     */
    FirstName(1),
    /**
     * <code>LastName = 2;</code>
     */
    LastName(2),
    /**
     * <code>Phone = 3;</code>
     */
    Phone(3),
    /**
     * <code>DateOfBirth = 4;</code>
     */
    DateOfBirth(4),
    /**
     * <code>Gender = 5;</code>
     */
    Gender(5),
    /**
     * <code>City = 6;</code>
     */
    City(6),
    /**
     * <code>State = 7;</code>
     */
    State(7),
    /**
     * <code>Zip = 8;</code>
     */
    Zip(8),
    /**
     * <code>Country = 9;</code>
     */
    Country(9),
    /**
     * <code>ExternalId = 10;</code>
     */
    ExternalId(10),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Email = 0;</code>
     */
    public static final int Email_VALUE = 0;
    /**
     * <code>FirstName = 1;</code>
     */
    public static final int FirstName_VALUE = 1;
    /**
     * <code>LastName = 2;</code>
     */
    public static final int LastName_VALUE = 2;
    /**
     * <code>Phone = 3;</code>
     */
    public static final int Phone_VALUE = 3;
    /**
     * <code>DateOfBirth = 4;</code>
     */
    public static final int DateOfBirth_VALUE = 4;
    /**
     * <code>Gender = 5;</code>
     */
    public static final int Gender_VALUE = 5;
    /**
     * <code>City = 6;</code>
     */
    public static final int City_VALUE = 6;
    /**
     * <code>State = 7;</code>
     */
    public static final int State_VALUE = 7;
    /**
     * <code>Zip = 8;</code>
     */
    public static final int Zip_VALUE = 8;
    /**
     * <code>Country = 9;</code>
     */
    public static final int Country_VALUE = 9;
    /**
     * <code>ExternalId = 10;</code>
     */
    public static final int ExternalId_VALUE = 10;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FBUserDataType valueOf(int value) {
      return forNumber(value);
    }

    public static FBUserDataType forNumber(int value) {
      switch (value) {
        case 0: return Email;
        case 1: return FirstName;
        case 2: return LastName;
        case 3: return Phone;
        case 4: return DateOfBirth;
        case 5: return Gender;
        case 6: return City;
        case 7: return State;
        case 8: return Zip;
        case 9: return Country;
        case 10: return ExternalId;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FBUserDataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FBUserDataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FBUserDataType>() {
            @java.lang.Override
            public FBUserDataType findValueByNumber(int number) {
              return FBUserDataType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return FBUserDataTypeVerifier.INSTANCE;
    }

    private static final class FBUserDataTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new FBUserDataTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return FBUserDataType.forNumber(number) != null;
            }
          };

    private final int value;

    private FBUserDataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FBUserDataType)
  }

  public interface FBSetUserDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FBSetUserDataRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @return The type.
     */
    cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType getType();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code FBSetUserDataRequest}
   */
  public  static final class FBSetUserDataRequest extends
      com.google.protobuf.GeneratedMessageLite<
          FBSetUserDataRequest, FBSetUserDataRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:FBSetUserDataRequest)
      FBSetUserDataRequestOrBuilder {
    private FBSetUserDataRequest() {
      value_ = "";
    }
    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType getType() {
      cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType result = cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType.forNumber(type_);
      return result == null ? cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
      bitField0_ |= 0x00000001;  type_ = value;
    }
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     * @param value The type to set.
     */
    private void setType(cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType value) {
      type_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .FBUserDataType type = 1;</code>
     */
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.String value_;
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string value = 2;</code>
     * @param value The value to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      value_ = value;
    }
    /**
     * <code>string value = 2;</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string value = 2;</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code FBSetUserDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:FBSetUserDataRequest)
        cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequestOrBuilder {
      // Construct using cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .FBUserDataType type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return instance.hasType();
      }
      /**
       * <code>optional .FBUserDataType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>optional .FBUserDataType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>optional .FBUserDataType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType getType() {
        return instance.getType();
      }
      /**
       * <code>optional .FBUserDataType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBUserDataType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>optional .FBUserDataType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FBSetUserDataRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "type_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u100c\u0000\u0002" +
                "\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest> parser = PARSER;
          if (parser == null) {
            synchronized (cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:FBSetUserDataRequest)
    private static final cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest DEFAULT_INSTANCE;
    static {
      FBSetUserDataRequest defaultInstance = new FBSetUserDataRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FBSetUserDataRequest.class, defaultInstance);
    }

    public static cat.durban.sergio.flutter_meta_appads_sdk.proto.SetUserDataMessage.FBSetUserDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FBSetUserDataRequest> PARSER;

    public static com.google.protobuf.Parser<FBSetUserDataRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
